# Generated by Django 2.2.4 on 2019-08-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
