# Generated by Django 2.2.4 on 2019-08-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_profileuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
