# Generated by Django 2.2.4 on 2019-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190820_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='event_status',
            field=models.BooleanField(null=True),
        ),
    ]
