# Generated by Django 2.2.4 on 2019-08-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190815_0243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
